-- TaskHub initial schema (SPEC §2 domain model).
-- Flyway owns the schema; Hibernate runs with ddl-auto=validate. Forward-only:
-- later sessions add new V* migrations (indexes, optimizations) — never edit this.

create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    username      varchar(100) not null unique,
    password_hash varchar(255) not null,
    created_at    timestamp with time zone not null default now()
);

-- User.roles ⊆ {USER, ADMIN} — element collection.
create table user_roles (
    user_id bigint      not null references users (id) on delete cascade,
    role    varchar(20) not null,
    primary key (user_id, role)
);

create table projects (
    id          bigint generated by default as identity primary key,
    name        varchar(150) not null,
    description varchar(2000),
    owner_id    bigint       not null references users (id),
    created_at  timestamp with time zone not null default now()
);

create table tags (
    id    bigint generated by default as identity primary key,
    name  varchar(50) not null unique,
    color varchar(20)
);

-- Task.status ∈ {TODO, IN_PROGRESS, DONE}; Task.priority ∈ {LOW, MEDIUM, HIGH}.
create table tasks (
    id          bigint generated by default as identity primary key,
    title       varchar(200) not null,
    description varchar(4000),
    status      varchar(20)  not null,
    priority    varchar(20)  not null,
    due_date    date,
    project_id  bigint       not null references projects (id) on delete cascade,
    assignee_id bigint       references users (id),
    created_at  timestamp with time zone not null default now()
);

-- Task 0..* Tag (many-to-many).
create table task_tag (
    task_id bigint not null references tasks (id) on delete cascade,
    tag_id  bigint not null references tags (id) on delete cascade,
    primary key (task_id, tag_id)
);
